In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = pd.read_csv('data_set.csv')
raw_data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0    ...        25.380          17.33           184.60      2019.0   
1    ...        24.990          23.41           158.80      1956.0   
2    ...        23.570          25.53           152.50      1709.0   
3    ...        14.910          26.50            98.87       567.7   
4    ...        22.540          16.67           152.20      1575.0   
..   ...           ...            ...              ...         ...   
564  ...        25.450          26.40           166.10      2027.0   
565  ...        23.690          38.25           155.00      1731.0   
566  ...        18.980          34.12           126.70      1124.0   
567  ...        25.740          39.42           184.60      1821.0   
568  ...         9.456          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...                      ...  
564                0.2216       

## Dataset without feature engineering (Orignal_Dataset) for PM 1

In [3]:
# Dropping Id Column
dataset1 = raw_data.drop('id', axis=1)

# Filling Na values with the mean of that column
for column in dataset1.columns[1:]:
    dataset1[column] = dataset1[column].fillna(dataset1[column].mean())

# Replacing target/diagnosis column with 1 and -1
dataset1.diagnosis.replace(['M', 'B'], [1, -1], inplace=True)
dataset1

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1        17.99         10.38          122.80     1001.0   
1            1        20.57         17.77          132.90     1326.0   
2            1        19.69         21.25          130.00     1203.0   
3            1        11.42         20.38           77.58      386.1   
4            1        20.29         14.34          135.10     1297.0   
..         ...          ...           ...             ...        ...   
564          1        21.56         22.39          142.00     1479.0   
565          1        20.13         28.25          131.20     1261.0   
566          1        16.60         28.08          108.30      858.1   
567          1        20.60         29.33          140.10     1265.0   
568         -1         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    .

## Dataset with feature engineering (Featured_Dataset) for PM 3

In [4]:
# Dropping Id Column
dataset3 = raw_data.drop('id', axis='columns')

# Normalising Data
for column in dataset3.columns[1:]:
    dataset3[column] = (dataset3[column] - dataset3[column].mean())/dataset3[column].std()

# Replacing target/diagnosis column with 1 and -1
dataset3.diagnosis.replace(['M', 'B'], [1, -1], inplace=True)

# Filling Na values with the mean of that column i.e 0;
dataset3.fillna(0, inplace=True)
dataset3

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1     1.101451     -2.071512        1.267272   0.983510   
1            1     1.835017     -0.353322        1.683156   1.907030   
2            1     1.584809      0.455786        1.563744   1.557513   
3            1    -0.766584      0.253509       -0.594733  -0.763792   
4            1     1.755405     -1.150804        1.773744   1.824624   
..         ...          ...           ...             ...        ...   
564          1     2.116502      0.720838        2.057863   2.341795   
565          1     1.709913      2.083301        1.613156   1.722326   
566          1     0.706235      2.043775        0.670212   0.577445   
567          1     1.843547      2.334403        1.979627   1.733693   
568         -1    -1.807224      1.220718       -1.816030  -1.346604   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0           1.567087          3.280628        2.648503             2.530249   
1          -0.826235         -0.486643       -0.025395             0.547662   
2           0.941382          1.052000        1.360467             2.035440   
3           3.280667          3.399917        1.912303             1.450431   
4           0.280125          0.538866        1.367992             1.427237   
..               ...               ...             ...                  ...   
564         1.040926          0.218868        1.943657             2.318924   
565         0.102368         -0.017817        0.690738             1.262558   
566        -0.839745         -0.038646        0.044965             0.105684   
567         1.524426          3.269267        3.291893             2.656528   
568        -3.109349         -1.149741       -1.115271            -1.260710   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         2.215566  ...      1.885031      -1.358098         2.301575   
1         0.001391  ...      1.804340      -0.368879         1.533776   
2         0.938859  ...      1.510541      -0.023953         1.346291   
3         2.864862  ...     -0.281217       0.133866        -0.249720   
4        -0.009552  ...      1.297434      -1.465481         1.337363   
..             ...  ...           ...            ...              ...   
564      -0.312314  ...      1.899514       0.117596         1.751022   
565      -0.217473  ...      1.535369       2.045599         1.420690   
566      -0.808406  ...      0.560868       1.373645         0.578492   
567       2.135315  ...      1.959515       2.235958         2.301575   
568      -0.819349  ...     -1.409652       0.763518        -1.431475   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      1.995136          1.306537           2.614365         2.105518   
1      1.884646         -0.375282          -0.430066        -0.147838   
2      1.451453          0.526944           1.081980         0.852589   
3     -0.550176          3.391291           3.889975         1.985735   
4      1.216442          0.220362          -0.313119         0.611107   
..          ...               ...                ...              ...   
564    2.009167          0.378033          -0.273077         0.662374   
565    1.490037         -0.690623          -0.394473         0.234988   
566    0.425471         -0.808876           0.350427         0.325065   
567    1.647881          1.429169           3.901415         3.192188   
568   -1.074743         -1.857384          -1.206491        -1.305420   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
0                2.294058        2.748204                 1.935312  
1                1.086129       -0.243675                 0.280943  
2                1.953282        1.151242                 0.201214  
3                2.173873        6.040726                 4.930672  
4                0.728618       -0.867590                -0.396751  
..                    .

## Dataset formed by rearranging the features of Orignal_Dataset for PM 4

In [5]:
# Rearranging Features
diagnosis = dataset1.diagnosis
dataset4 = dataset1.sample(frac=1, axis=1)
dataset4.drop('diagnosis', axis=1, inplace=True)
dataset4.insert(0, 'diagnosis', diagnosis)
dataset4

diagnosis  symmetry_mean  concavity_se  radius_worst  \
0            1         0.2419       0.05373        25.380   
1            1         0.1812       0.01860        24.990   
2            1         0.2069       0.03832        23.570   
3            1         0.2597       0.05661        14.910   
4            1         0.1809       0.05688        22.540   
..         ...            ...           ...           ...   
564          1         0.1726       0.05198        25.450   
565          1         0.1752       0.03950        23.690   
566          1         0.1590       0.04730        18.980   
567          1         0.2397       0.07117        25.740   
568         -1         0.1587       0.00000         9.456   

     fractal_dimension_mean  perimeter_worst  concavity_mean  texture_se  \
0                   0.07871           184.60         0.30010      0.9053   
1                   0.05667           158.80         0.08690      0.7339   
2                   0.05999           152.50         0.19740      0.7869   
3                   0.09744            98.87         0.24140      1.1560   
4                   0.05883           152.20         0.19800      0.7813   
..                      ...              ...             ...         ...   
564                 0.05623           166.10         0.24390      1.2560   
565                 0.05533           155.00         0.14400      2.4630   
566                 0.05648           126.70         0.09251      1.0750   
567                 0.07016           184.60         0.35140      1.5950   
568                 0.05884            59.16         0.00000      1.4280   

     smoothness_se  perimeter_se  ...  smoothness_mean  texture_worst  \
0         0.006399         8.589  ...          0.11840          17.33   
1         0.005225         3.398  ...          0.08474          23.41   
2         0.006150         4.585  ...          0.10960          25.53   
3         0.009110         3.445  ...          0.14250          26.50   
4         0.011490         5.438  ...          0.10030          16.67   
..             ...           ...  ...              ...            ...   
564       0.010300         7.673  ...          0.11100          26.40   
565       0.005769         5.203  ...          0.09780          38.25   
566       0.005903         3.425  ...          0.08455          34.12   
567       0.006522         5.772  ...          0.11780          39.42   
568       0.007189         2.548  ...          0.05263          30.37   

     area_worst  smoothness_worst  compactness_se  concave_points_mean  \
0        2019.0           0.16220         0.04904              0.14710   
1        1956.0           0.12380         0.01308              0.07017   
2        1709.0           0.14440         0.04006              0.12790   
3         567.7           0.20980         0.07458              0.10520   
4        1575.0           0.13740         0.02461              0.10430   
..          ...               ...             ...                  ...   
564      2027.0           0.14100         0.02891              0.13890   
565      1731.0           0.11660         0.02423              0.09791   
566      1124.0           0.11390         0.03731              0.05302   
567      1821.0           0.16500         0.06158              0.15200   
568       268.6           0.08996         0.00466              0.00000   

     radius_mean  perimeter_mean  compactness_worst  concave_points_worst  
0          17.99          122.80            0.66560                0.2654  
1          20.57          132.90            0.18660                0.1860  
2          19.69          130.00            0.42450                0.2430  
3          11.42           77.58            0.86630                0.2575  
4          20.29          135.10            0.20500                0.1625  
..           ...             ...                ...                   ...  
564        21.56          142.00            0.21130          

## Activating Function for Perceptron

In [6]:
def func(x):
    if x>=0:
        return 1
    else:
        return -1

## Perceptron Algorithm

In [7]:
def train_perceptron(training_set):
    w = np.zeros(31)
    for i in range(3000):
        for training_example in training_set:
            x = np.append(training_example[1:], 1)
            y = training_example[0]
            if y*func(w.dot(x))<0:
                w = w + y*x  
    return w

## Evaluation

In [8]:
def evaluate_perceptron(testing_set, w):
    c_mat = np.zeros((2, 2))
    for testing_example in testing_set:
        x = np.append(testing_example[1:], 1)
        y = testing_example[0]
        if y==1 and func(w.dot(x))==1:
            c_mat[1][1]+=1
            
        elif y==1 and func(w.dot(x))==-1:
            c_mat[1][0]+=1
            
        elif y==-1 and func(w.dot(x))==-1: 
            c_mat[0][0]+=1
            
        else:
            c_mat[0][1]+=1
            
    return c_mat

## Evaluation Metrics

In [9]:
def accuracy(c_mat):
    return (c_mat[0][0]+c_mat[1][1])/(c_mat[0][0] + c_mat[0][1] + c_mat[1][0] + c_mat[1][1])*100

def precision(c_mat):
    return (c_mat[0][0])/(c_mat[1][0] + c_mat[0][0])*100

def recall(c_mat):
    return (c_mat[1][1])/(c_mat[1][0] + c_mat[1][1])*100

## Spilting the Dataset into Training Data and Testing Data

In [10]:
training_data = dataset1.sample(frac=2/3)
training_data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
64           1       12.680         23.84           82.69      499.0   
401         -1       11.930         10.91           76.14      442.7   
139         -1       11.280         13.39           73.00      384.8   
105          1       13.110         15.56           87.21      530.2   
537         -1       11.690         24.44           76.37      406.4   
..         ...          ...           ...             ...        ...   
47           1       13.170         18.66           85.98      534.6   
479          1       16.250         19.51          109.80      815.8   
206         -1        9.876         17.27           62.92      295.4   
228         -1       12.620         23.97           81.35      496.4   
229          1       12.830         22.33           85.26      503.2   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
64           0.11220           0.12620         0.11280              0.06873   
401          0.08872           0.05242         0.02606              0.01796   
139          0.11640           0.11360         0.04635              0.04796   
105          0.13980           0.17650         0.20710              0.09601   
537          0.12360           0.15520         0.04515              0.04531   
..               ...               ...             ...                  ...   
47           0.11580           0.12310         0.12260              0.07340   
479          0.10260           0.18930         0.22360              0.09194   
206          0.10890           0.07232         0.01756              0.01952   
228          0.07903           0.07529         0.05438              0.02036   
229          0.10880           0.17990         0.16950              0.06861   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
64          0.1905  ...         17.09          33.47           111.80   
401         0.1601  ...         13.80          20.14            87.64   
139         0.1771  ...         11.92          15.77            76.53   
105         0.1925  ...         16.31          22.40           106.40   
537         0.2131  ...         12.98          32.19            86.12   
..             ...  ...           ...            ...              ...   
47          0.2128  ...         15.67          27.95           102.80   
479         0.2151  ...         17.39          23.05           122.10   
206         0.1934  ...         10.42          23.22            67.08   
228         0.1514  ...         14.20          31.31            90.67   
229         0.2123  ...         15.20          30.15           105.30   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
64        888.3            0.1851             0.4061          0.40240   
401       589.5            0.1374             0.1575          0.15140   
139       434.0            0.1367             0.1822          0.08669   
105       827.2            0.1862             0.4099          0.63760   
537       487.7            0.1768             0.3251          0.13950   
..          ...               ...                ...              ...   
47        759.4            0.1786             0.4166          0.50060   
479       939.7            0.1377             0.4462          0.58970   
206       331.6            0.1415             0.1247          0.06213   
228       624.0            0.1227             0.3454          0.39110   
229       706.0            0.1777             0.5343          0.62820   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
64                0.17160          0.3383                  0.10310  
401               0.06876          0.2460                  0.07262  
139               0.08611          0.2102                  0.06784  
105               0.19860          0.3147                  0.14050  
537               0.13080          0.2803                  0.09970  
..                    .

In [11]:
testing_data = dataset1.drop(training_data.index)
testing_data

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
3            1        11.42         20.38           77.58      386.1   
5            1        12.45         15.70           82.57      477.1   
6            1        18.25         19.98          119.60     1040.0   
7            1        13.71         20.83           90.20      577.9   
8            1        13.00         21.82           87.50      519.8   
..         ...          ...           ...             ...        ...   
560         -1        14.05         27.15           91.38      600.4   
561         -1        11.20         29.37           70.67      386.0   
562          1        15.22         30.62          103.40      716.9   
563          1        20.92         25.09          143.00     1347.0   
568         -1         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
3            0.14250           0.28390         0.24140              0.10520   
5            0.12780           0.17000         0.15780              0.08089   
6            0.09463           0.10900         0.11270              0.07400   
7            0.11890           0.16450         0.09366              0.05985   
8            0.12730           0.19320         0.18590              0.09353   
..               ...               ...             ...                  ...   
560          0.09929           0.11260         0.04462              0.04304   
561          0.07449           0.03558         0.00000              0.00000   
562          0.10480           0.20870         0.25500              0.09429   
563          0.10990           0.22360         0.31740              0.14740   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
3           0.2597  ...        14.910          26.50            98.87   
5           0.2087  ...        15.470          23.75           103.40   
6           0.1794  ...        22.880          27.66           153.20   
7           0.2196  ...        17.060          28.14           110.60   
8           0.2350  ...        15.490          30.73           106.20   
..             ...  ...           ...            ...              ...   
560         0.1537  ...        15.300          33.17           100.20   
561         0.1060  ...        11.920          38.30            75.19   
562         0.2128  ...        17.520          42.79           128.70   
563         0.2149  ...        24.290          29.41           179.10   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
3         567.7           0.20980            0.86630           0.6869   
5         741.6           0.17910            0.52490           0.5355   
6        1606.0           0.14420            0.25760           0.3784   
7         897.0           0.16540            0.36820           0.2678   
8         739.3           0.17030            0.54010           0.5390   
..          ...               ...                ...              ...   
560       706.7           0.12410            0.22640           0.1326   
561       439.6           0.09267            0.05494           0.0000   
562       915.0           0.14170            0.79170           1.1700   
563      1819.0           0.14070            0.41860           0.6599   
568       268.6           0.08996            0.06444           0.0000   

     concave_points_worst  symmetry_worst  fractal_dimension_worst  
3                  0.2575          0.6638                  0.17300  
5                  0.1741          0.3985                  0.12440  
6                  0.1932          0.3063                  0.08368  
7                  0.1556          0.3196                  0.11510  
8                  0.2060          0.4378                  0.10720  
..                    .

## Training Perceptron using the above mentioned algorithm

In [12]:
training_set = training_data.to_numpy()
w1 = train_perceptron(training_set)
w1

array([-3.62185670e+04,  1.11090300e+04, -1.09173443e+05,  3.30800000e+03,
        5.32343280e+02,  3.39898958e+03,  4.74215442e+03,  2.09692271e+03,
        7.28007300e+02,  8.48196600e+01, -1.11611730e+03, -5.89185780e+03,
        1.04273791e+04,  6.47434600e+03,  1.14970067e+02,  7.43217750e+02,
        1.15379838e+03,  3.08671770e+02,  1.75039697e+02,  7.41746903e+01,
       -3.44611950e+04,  4.36129000e+04,  2.94716300e+04,  5.34849259e+03,
        1.11969948e+03,  1.08062419e+04,  1.33426462e+04,  4.05393647e+03,
        2.21064260e+03,  8.77005220e+02, -5.03600000e+03])

## Evaluating the Model on Testing Data

In [13]:
testing_set = testing_data.to_numpy()
n = evaluate_perceptron(testing_set, w1)
print(n)
print(f"Accuracy: {accuracy(n)}")
print(f"Precision: {precision(n)}")
print(f"Recall: {recall(n)}")

[[103.   7.]
 [ 10.  70.]]
Accuracy: 91.05263157894737
Precision: 91.1504424778761
Recall: 87.5


In [14]:
training_set = dataset1.to_numpy()
testing_set = dataset1.to_numpy()

w = train_perceptron(training_set)
c_mat = evaluate_perceptron(testing_set, w)

print(c_mat)
print(f"Accuracy: {accuracy(c_mat)}")
print(f"Precision: {precision(c_mat)}")
print(f"Recall: {recall(c_mat)}")

[[357.   0.]
 [ 54. 158.]]
Accuracy: 90.50966608084359
Precision: 86.86131386861314
Recall: 74.52830188679245


## Perceptron Model 1

In [15]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
training_sets = []
w = np.zeros(31)
for i in range(10):
    
    training_data = dataset1.sample(frac=2/3)
    testing_data = dataset1.drop(training_data.index)
    training_sets.append(training_data)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[117.   1.]
 [ 14.  58.]]
Accuracy = 92.10526315789474
Precision = 89.31297709923665
Recall = 80.55555555555556


Model No.2
Confusion Matrix:
[[103.  16.]
 [  6.  65.]]
Accuracy = 88.42105263157895
Precision = 94.4954128440367
Recall = 91.54929577464789


Model No.3
Confusion Matrix:
[[95. 20.]
 [ 2. 73.]]
Accuracy = 88.42105263157895
Precision = 97.9381443298969
Recall = 97.33333333333334


Model No.4
Confusion Matrix:
[[107.  11.]
 [  7.  65.]]
Accuracy = 90.52631578947368
Precision = 93.85964912280701
Recall = 90.27777777777779


Model No.5
Confusion Matrix:
[[104.  18.]
 [  3.  65.]]
Accuracy = 88.94736842105263
Precision = 97.19626168224299
Recall = 95.58823529411765


Model No.6
Confusion Matrix:
[[113.   1.]
 [ 13.  63.]]
Accuracy = 92.63157894736842
Precision = 89.68253968253968
Recall = 82.89473684210526


Model No.7
Confusion Matrix:
[[93. 25.]
 [ 3. 69.]]
Accuracy = 85.26315789473684
Precision = 96.875
Recall = 95.83333333333334


Model No.8
Co

## Perceptron Model 2

In [16]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
w = np.zeros(31)
for i in range(10):
    
    training_data = training_sets[i].sample(frac=1)
    testing_data = dataset1.drop(training_data.index)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[115.   3.]
 [  8.  64.]]
Accuracy = 94.21052631578948
Precision = 93.4959349593496
Recall = 88.88888888888889


Model No.2
Confusion Matrix:
[[98. 21.]
 [ 3. 68.]]
Accuracy = 87.36842105263159
Precision = 97.02970297029702
Recall = 95.77464788732394


Model No.3
Confusion Matrix:
[[107.   8.]
 [  7.  68.]]
Accuracy = 92.10526315789474
Precision = 93.85964912280701
Recall = 90.66666666666666


Model No.4
Confusion Matrix:
[[114.   4.]
 [ 16.  56.]]
Accuracy = 89.47368421052632
Precision = 87.6923076923077
Recall = 77.77777777777779


Model No.5
Confusion Matrix:
[[105.  17.]
 [  4.  64.]]
Accuracy = 88.94736842105263
Precision = 96.3302752293578
Recall = 94.11764705882352


Model No.6
Confusion Matrix:
[[93. 21.]
 [ 0. 76.]]
Accuracy = 88.94736842105263
Precision = 100.0
Recall = 100.0


Model No.7
Confusion Matrix:
[[114.   4.]
 [ 10.  62.]]
Accuracy = 92.63157894736842
Precision = 91.93548387096774
Recall = 86.11111111111111


Model No.8
Confusion Matrix

## Perceptron Model 3

In [18]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
w = np.zeros(31)
for i in range(10):
    
    training_data = dataset3.sample(frac=2/3)
    testing_data = dataset3.drop(training_data.index)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[121.   4.]
 [  4.  61.]]
Accuracy = 95.78947368421052
Precision = 96.8
Recall = 93.84615384615384


Model No.2
Confusion Matrix:
[[114.   6.]
 [  3.  67.]]
Accuracy = 95.26315789473684
Precision = 97.43589743589743
Recall = 95.71428571428572


Model No.3
Confusion Matrix:
[[119.   3.]
 [  7.  61.]]
Accuracy = 94.73684210526315
Precision = 94.44444444444444
Recall = 89.70588235294117


Model No.4
Confusion Matrix:
[[106.   8.]
 [  1.  75.]]
Accuracy = 95.26315789473684
Precision = 99.06542056074767
Recall = 98.68421052631578


Model No.5
Confusion Matrix:
[[111.   5.]
 [  5.  69.]]
Accuracy = 94.73684210526315
Precision = 95.6896551724138
Recall = 93.24324324324324


Model No.6
Confusion Matrix:
[[117.   8.]
 [  3.  62.]]
Accuracy = 94.21052631578948
Precision = 97.5
Recall = 95.38461538461539


Model No.7
Confusion Matrix:
[[115.   4.]
 [  2.  69.]]
Accuracy = 96.84210526315789
Precision = 98.29059829059828
Recall = 97.1830985915493


Model No.8
Confusion

## Perceptron Model 4

In [19]:
accuracy_list = np.zeros(10)
precision_list = np.zeros(10)
recall_list = np.zeros(10)
w = np.zeros(31)
for i in range(10):
    
    training_data = dataset4.sample(frac=2/3)
    testing_data = dataset4.drop(training_data.index)
    training_set = training_data.to_numpy()
    testing_set = testing_data.to_numpy()
    
    w = train_perceptron(training_set)
    c_mat = evaluate_perceptron(testing_set, w)
    
    print(f"Model No.{i+1}")
    print(f"Confusion Matrix:\n{c_mat}")
    print(f"Accuracy = {accuracy(c_mat)}")
    print(f"Precision = {precision(c_mat)}")
    print(f"Recall = {recall(c_mat)}")
    
    accuracy_list[i] =  accuracy(c_mat)
    precision_list[i] = precision(c_mat)
    recall_list[i] =  recall(c_mat)
    print("\n")
    
print(f"Accuracy:\n Mean = {accuracy_list.mean()}  Standard Deviation = {accuracy_list.std()}")
print(f"Precision:\n Mean = {precision_list.mean()}  Standard Deviation = {precision_list.std()}")
print(f"Recall:\n Mean = {recall_list.mean()}  Standard Deviation = {recall_list.std()}")

Model No.1
Confusion Matrix:
[[84. 34.]
 [ 0. 72.]]
Accuracy = 82.10526315789474
Precision = 100.0
Recall = 100.0


Model No.2
Confusion Matrix:
[[121.   3.]
 [ 10.  56.]]
Accuracy = 93.15789473684211
Precision = 92.36641221374046
Recall = 84.84848484848484


Model No.3
Confusion Matrix:
[[124.   1.]
 [ 14.  51.]]
Accuracy = 92.10526315789474
Precision = 89.85507246376811
Recall = 78.46153846153847


Model No.4
Confusion Matrix:
[[121.   1.]
 [ 17.  51.]]
Accuracy = 90.52631578947368
Precision = 87.68115942028986
Recall = 75.0


Model No.5
Confusion Matrix:
[[113.   3.]
 [  6.  68.]]
Accuracy = 95.26315789473684
Precision = 94.9579831932773
Recall = 91.8918918918919


Model No.6
Confusion Matrix:
[[104.  10.]
 [  6.  70.]]
Accuracy = 91.57894736842105
Precision = 94.54545454545455
Recall = 92.10526315789474


Model No.7
Confusion Matrix:
[[98. 16.]
 [ 6. 70.]]
Accuracy = 88.42105263157895
Precision = 94.23076923076923
Recall = 92.10526315789474


Model No.8
Confusion Matrix:
[[98. 15.]

Observation:
1. There is no substantial difference in results after changing the order of tuples in   training data as PM1 and PM3 has similar evaluation metrics.

2. Results improve substantially in PM3 as compared to PM1, PM2 and PM4 due to normalizations.

3. There is no substatial difference in results after chaniging the order of features in training data as PM1 and PM4 has similar evaluation metrics.